Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"

  config.vm.network "public_network"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y nginx

    sed -i 's/listen 80 default_server;/listen 82 default_server;/' /etc/nginx/sites-available/default
    sed -i 's/listen \\[::\\]:80 default_server;/listen [::]:82 default_server;/' /etc/nginx/sites-available/default

    systemctl restart nginx
    systemctl enable nginx
  SHELL

end